<?php
ob_start();
include("template/_header.php");
include("template/_banner-area.php");
include("template/_top-sale.php");
include("template/_special-price.php");
include("template/_banner-ads.php");
include("template/_new-phones.php");
include("template/_blogs.php");
include("template/_footer.php");
ob_end_flush();